Container updates and issues
ansible-lockdown/RHEL8-CIS pull request #297
Opened 2023-06-06 13:40 UTC by uk-bolly

**Overall Review of Changes:**
Container updates
lint
ansible version alignment

**Issue Fixes:**
#295 
#296 

**Enhancements:**
issues container some great improvements

**How has this been tested?:**
Manually with multiple options

2023-06-06 17:21 UTC, bbaassssiiee requested changes
AD-SUPPORT is the name of the module.

2023-06-06 17:21 UTC, bbaassssiiee commented on vars/main.yml
> +    - 'AD-Support'
Should be all-caps

2023-06-06 17:41 UTC, uk-bolly commented
> AD-SUPPORT is the name of the module.

Great spot, updated

2023-06-06 17:42 UTC, uk-bolly commented on vars/main.yml
> +    - 'AD-Support'
Great spot updated

2023-06-07 12:59 UTC, MrSteve81 approved these changes
Looks good to Me!

2023-06-08 10:45 UTC, bbaassssiiee approved these changes
I verified the fixes of my reported issues with the branch. Please merge and tag ASAP!

2023-06-08 10:47 UTC, merged